# Generated by Django 5.0 on 2023-12-11 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0001_initial'),
    ]

    operations = [
        # Wrap operation with SeparateDatabaseAndState
        # to avoid database modifications when remove field
        migrations.SeparateDatabaseAndState(
            state_operations=[

                migrations.RemoveField(
                    model_name='letting',
                    name='address',
                ),
            ],
            database_operations=[],  # Empty to avoid changes
        ),

        # Same logic when deleting model from oc_lettings_site app
        migrations.SeparateDatabaseAndState(
            state_operations=[

                migrations.DeleteModel(
                    name='Address',
                ),
                migrations.DeleteModel(
                    name='Letting',
                ),
            ],
            # Database changes : Rename table with AlterModelTable, to stick to lettings app
            database_operations=[
                migrations.AlterModelTable(
                    name='Address',
                    table='lettings_address',
                ),
                migrations.AlterModelTable(
                    name='Letting',
                    table='lettings_letting',
                ),
            ]
        ),
    ]
