# Generated by Django 5.0 on 2023-12-11 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0002_remove_letting_address_delete_address_delete_letting'),
    ]

    operations = [
        # Wrap operation with SeparateDatabaseAndState
        # to avoid database modifications when remove field
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Profile',
                ),
            ],
            # Data Base changes : Rename table with AlterModelTable, to stick to profiles app
            database_operations=[
                migrations.AlterModelTable(
                    name='Profile',
                    table='profiles_profile'
                ),
            ],
        ),

    ]
